### ISSUE TITLE
Lua language server telemetry config option is deprecated

### ISSUE THREAD

**Issue by nullromo** [collindutter/.dotfiles#1]
[Config line](https://github.com/collindutter/.dotfiles/blob/8244f5909fde38f94c55827e00aedd696e6f72cb/.config/nvim/lua/plugins/init.lua#L186)

[Reference](https://luals.github.io/wiki/settings/#telemetry)

**Comment by collindutter** [comment]
Fixed in https://github.com/collindutter/.dotfiles/commit/5882329d0c1fb66e9f8f405a2db3153953d77f84
